export const games = [
  {
    id: "never-have-i-ever",
    name: "Never Have I Ever",
    description: "Reveal secrets through classic confessions",
    icon: "👁️",
    mature: false,
    players: "3-12",
    duration: "15-30 min",
    category: "Classic",
    popularity: 5,
    questions: 150,
  },
  {
    id: "truth-or-dare",
    name: "Truth or Dare",
    description: "Choose your adventure - reveal or perform",
    icon: "🎯",
    mature: false,
    players: "3-10",
    duration: "20-45 min",
    category: "Classic",
    popularity: 5,
    questions: 200,
  },
  {
    id: "whos-most-likely",
    name: "Who's Most Likely To",
    description: "Point fingers and laugh together",
    icon: "👆",
    mature: false,
    players: "4-15",
    duration: "10-25 min",
    category: "Classic",
    popularity: 4,
    questions: 180,
  },
  {
    id: "would-you-rather",
    name: "Would You Rather",
    description: "Make impossible choices together",
    icon: "🤔",
    mature: false,
    players: "3-12",
    duration: "15-35 min",
    category: "Classic",
    popularity: 4,
    questions: 160,
  },
  {
    id: "if-you-had-to",
    name: "If You Had To",
    description: "Hypothetical scenarios that spark debate",
    icon: "💭",
    mature: false,
    players: "3-10",
    duration: "20-40 min",
    category: "Creative",
    popularity: 3,
    questions: 120,
  },
  {
    id: "drink-if",
    name: "Drink If",
    description: "The ultimate drinking companion",
    icon: "🥃",
    mature: true,
    players: "3-15",
    duration: "15-60 min",
    category: "Drinking",
    popularity: 5,
    questions: 250,
  },
  {
    id: "hot-seat",
    name: "Hot Seat",
    description: "One player, everyone else asks questions",
    icon: "🔥",
    mature: false,
    players: "4-10",
    duration: "20-35 min",
    category: "Interactive",
    popularity: 3,
    questions: 140,
  },
  {
    id: "paranoia",
    name: "Paranoia",
    description: "Whispered questions, public answers",
    icon: "🤫",
    mature: true,
    players: "5-12",
    duration: "25-45 min",
    category: "Mystery",
    popularity: 4,
    questions: 130,
  },
  {
    id: "kiss-marry-kill",
    name: "Kiss Marry Kill",
    description: "The classic dilemma game",
    icon: "💋",
    mature: true,
    players: "3-10",
    duration: "15-30 min",
    category: "Classic",
    popularity: 4,
    questions: 110,
  },
  {
    id: "spin-the-bottle",
    name: "Spin the Bottle",
    description: "Let fate decide your next move",
    icon: "🍾",
    mature: true,
    players: "4-12",
    duration: "20-40 min",
    category: "Classic",
    popularity: 3,
    questions: 100,
  },
  {
    id: "rapid-fire",
    name: "Rapid Fire",
    description: "Quick questions, quicker answers",
    icon: "⚡",
    mature: false,
    players: "3-10",
    duration: "10-20 min",
    category: "Fast-Paced",
    popularity: 3,
    questions: 200,
  },
  {
    id: "strip-or-sip",
    name: "Strip or Sip",
    description: "Choose your consequence wisely",
    icon: "👕",
    mature: true,
    players: "4-8",
    duration: "30-60 min",
    category: "Adult",
    popularity: 4,
    questions: 120,
  },
  {
    id: "emoji-decode",
    name: "Emoji Decode",
    description: "Guess the phrase from emojis",
    icon: "😎",
    mature: false,
    players: "3-12",
    duration: "15-25 min",
    category: "Creative",
    popularity: 3,
    questions: 150,
  },
  {
    id: "role-roulette",
    name: "Role Roulette",
    description: "Act out random characters and scenarios",
    icon: "🎭",
    mature: false,
    players: "4-10",
    duration: "20-35 min",
    category: "Creative",
    popularity: 3,
    questions: 140,
  },
  {
    id: "indian-drinking-game",
    name: "Ultimate Indian Drinking Game",
    description: "Bollywood meets party games",
    icon: "🇮🇳",
    mature: true,
    players: "4-12",
    duration: "30-60 min",
    new: true,
    category: "Cultural",
    popularity: 4,
    questions: 180,
  },
  {
    id: "drama-dol",
    name: "Drama-Dol Act or Get Sloshed",
    description: "Act it out or drink up",
    icon: "🎬",
    mature: true,
    players: "4-10",
    duration: "25-45 min",
    new: true,
    category: "Performance",
    popularity: 4,
    questions: 160,
  },
  {
    id: "cards-against-humanity",
    name: "Cards Against Humanity",
    description: "The party game for horrible people",
    icon: "🃏",
    mature: true,
    players: "4-20",
    duration: "30-90 min",
    new: true,
    category: "Card Game",
    popularity: 5,
    questions: 300,
  },
  {
    id: "custom-game",
    name: "Custom Game",
    description: "Create your own rules and content",
    icon: "⚙️",
    mature: false,
    players: "2-20",
    duration: "Variable",
    category: "Custom",
    popularity: 2,
    questions: 0,
  },
]
